# Generated by Django 3.0.4 on 2020-04-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macro', '0002_macroinput'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
    ]
